<!-- Plugins css start-->
<link rel="stylesheet" type="text/css" href="css/vendors/slick.css">
<link rel="stylesheet" type="text/css" href="css/vendors/slick-theme.css">
<link rel="stylesheet" type="text/css" href="css/vendors/scrollbar.css">
<link rel="stylesheet" type="text/css" href="css/vendors/animate.css">
<link rel="stylesheet" type="text/css" href="css/vendors/datatables.css">
<link rel="stylesheet" type="text/css" href="css/vendors/datatable/select.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="css/vendors/prism.css">
<link rel="stylesheet" type="text/css" href="css/vendors/vector-map.css">